- name: Create docker network 'web'
  community.general.docker_network:
    name: web

- name: Install elasticsearch
  community.docker.docker_container:
    name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.9
    restart_policy: unless-stopped
    recreate: true
    pull: true
    env:
      discovery.type: "single-node"
    network_mode: bridge
    exposed_ports: 9200
    published_ports:
      - "127.0.0.1:9200:9200"
      - "127.0.0.1:9300:9300"
    networks:
      - name: web
        aliases:
          - elasticsearch
    labels:
      traefik.enable: "false"
    volumes:
      - esdata:/usr/share/elasticsearch/data
